### ISSUE TITLE
SOC Accuracy & Certified Accuracy

### ISSUE THREAD

**Issue by araujoalexandre** [berndprach/1LipschitzLayersCompared#1]
Hi, 

Have you considered the following message from the authors of the SOC layer in their follow-up paper [1] ?

> Since SOC is an approximation, the Lipschitz constant of each SOC layer can be slightly more than 1 and if we use a large number of SOC layers (e.g. 41 in LipConvnet40), the Lipschitz constant of the full network (Lip(f)) can be significantly larger than 1. To mitigate this issue, we take the following steps: (a) We use a large number of terms (k = 15) during test time to approximate the exponential which results in a small approximation error (using the error bound in Singla and Feizi [2021]) and (b) We compute Lip(f) by multiplying the lipschitz constant of all SOC layers (using the power method) and then divide the certificate by Lip(f).

[1] Improved techniques for deterministic l2 robustness 
https://proceedings.neurips.cc/paper_files/paper/2022/file/66c9de41210338c9581d5313125b7486-Paper-Conference.pdf

**Comment by berndprach** [comment]
Hi, thanks for your interest. We did run the power method for all linear layers, to ensure that they are actually 1-Lipschitz. For the methods reported in the main paper, the Lipschitz constant was always at most 1 with our implementation.
