### ISSUE TITLE
SLL new implementation 

### ISSUE THREAD

**Issue by araujoalexandre** [berndprach/1LipschitzLayersCompared#2]
Hi, 

The SLL implementation with the epsilon is in fact not 1-Lipschitz as explained in the recent update in paper [1], Appendix D. 
We have updated the code with a new implementation that is stable and guaranteed to be 1-Lipschitz.

https://github.com/araujoalexandre/Lipschitz-SLL-Networks/blob/main/core/models/layers.py

[1] [A Unified Algebraic Perspective on Lipschitz Neural Networks](https://arxiv.org/abs/2303.03169)

**Comment by fabiobrau** [comment]
Hi, thanks for sharing such a recent update. We will mention it in the code. However, we believe our implementation is still 1-Lipschitz, and it's similar to the one you mention by Kai Hu.
A further epsilon to avoid zero-division has been included, [Line 77](https://github.com/berndprach/1LipschitzLayersCompared/blob/e839b6dc804b0cebb33d2527d471be32a73879cb/models/layers/lipschitz/sll.py#L77C18-L77C18), but this does not cause the lip constant to exceed 1.

**Comment by araujoalexandre** [comment]
Thanks, I checked the code and you are right!
